# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCapitulo',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('dataFundacao', models.DateField()),
                ('dataInstalacao', models.DateField()),
                ('mestreConselheiro', models.CharField(max_length=128)),
                ('avaliador', models.ForeignKey(db_column='avaliador_capitulo_id', on_delete=django.db.models.deletion.CASCADE, related_name='avaliador_cap', to='main.Usuario')),
                ('usuarioCap', models.ForeignKey(db_column='usuario_capitulo_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cap', to='main.Usuario')),
            ],
            options={
                'db_table': 'usuario_capitulo',
            },
        ),
    ]
