# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapa', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo_User',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('data_fundacao', models.DateField()),
                ('data_instalacao', models.DateField()),
                ('mestre_conselheiro', models.CharField(max_length=128)),
                ('regiao', models.CharField(choices=[('R1', '1º Região'), ('R2', '2º Região'), ('R3', '3º Região'), ('R4', '4º Região'), ('R5', '5º Região'), ('R6', '6º Região'), ('R7', '7º Região')], default='R1', max_length=2)),
                ('foto', models.ImageField(null=True, upload_to='fotos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capitulo_user',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.CharField(max_length=500)),
                ('planejamento', models.CharField(max_length=500)),
                ('abrangencia', models.CharField(max_length=500)),
                ('resultado', models.CharField(max_length=500)),
                ('data_realizacao', models.DateField()),
                ('data_envio', models.DateField()),
                ('conclusao', models.CharField(max_length=500)),
                ('arquivo_zip', models.FileField(upload_to='arquivozip/')),
                ('observacoes', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('S1', 'Aprovado'), ('S2', 'Negado'), ('S3', 'Correção'), ('S4', 'Enviado')], default='S4', max_length=2)),
                ('pontuacao_bonus', models.IntegerField(null=True)),
                ('capitulo', models.ForeignKey(db_column='usuario_capitulo', on_delete=django.db.models.deletion.CASCADE, related_name='capitulo_user', to='capitulo.Capitulo_User')),
                ('territorio', models.ForeignKey(db_column='territorio', on_delete=django.db.models.deletion.CASCADE, related_name='territorio', to='mapa.Territorio')),
            ],
            options={
                'db_table': 'formulario',
            },
        ),
    ]
