# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.CharField(max_length=500)),
                ('planejamento', models.CharField(max_length=500)),
                ('abrangencia', models.CharField(max_length=500)),
                ('resultado', models.CharField(max_length=500)),
                ('dataRealizacao', models.DateField()),
                ('dataEnvio', models.DateField()),
                ('territorio', models.CharField(max_length=30)),
                ('observacoes', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('S1', 'Aprovado'), ('S2', 'Negado'), ('S3', 'Correção'), ('S4', 'Enviado')], default='S4', max_length=2)),
                ('pontuacaoBonus', models.IntegerField()),
            ],
        ),
    ]
