# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0002_formulario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formulario',
            table='formulario',
        ),
    ]
