# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0003_auto_20171002_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='arquivoZip',
            field=models.ImageField(default=1, upload_to='arquivozip/'),
            preserve_default=False,
        ),
    ]
