# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0005_auto_20171004_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='conclusao',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
