# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0006_formulario_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='observacoes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='pontuacaoBonus',
            field=models.IntegerField(null=True),
        ),
    ]
