# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0007_auto_20171004_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='arquivozip',
            field=models.FileField(upload_to='arquivozip/'),
        ),
    ]
