# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0009_formulario_capitulouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='capituloUser',
            field=models.ForeignKey(db_column='usuario_capitulo_form_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_cap_form', to='main.Usuario'),
        ),
    ]
