# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0011_auto_20171005_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo_user',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
    ]
