# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='territorio',
            unique_together=set([('nome',)]),
        ),
    ]
