# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorio',
            name='foto',
            field=models.ImageField(default='fotos/territorios/brasil.png', upload_to='fotos/territorios/'),
            preserve_default=False,
        ),
    ]
