# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(max_length=128)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contato',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(choices=[('R1', '1º Região'), ('R2', '2º Região'), ('R3', '3º Região'), ('R4', '4º Região'), ('R5', '5º Região'), ('R6', '6º Região'), ('R7', '7º Região')], default='R1', max_length=2)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('tipoUsuario', models.CharField(choices=[('AVA', 'Avaliador'), ('CAP', 'Capítulo')], default='AVA', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
