# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capitulo', '0011_auto_20171005_1459'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
