# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171005_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
